version: '3.8'
services:
  pickup:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./server/db.json:/usr/src/app/server/db.json
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=change-me
      - SESSION_SECRET=change-me
